
export const SIGNUP_TODO_LOADING="SIGNUP_TODO_LOADING";
export const SIGNUP_TODO_SUCCESS="SIGNUP_TODO_SUCCESS";
export const SIGNUP_TODO_ERROR="SIGNUP_TODO_ERROR";

export const VERIFY_TODO_LOADING="VERIFY_TODO_LOADING";
export const VERIFY_TODO_SUCCESS="VERIFY_TODO_SUCCESS";
export const VERIFY_TODO_ERROR="VERIFY_TODO_ERROR";

export const LOGIN_TODO_LOADING="LOGIN_TODO_LOADING";
export const LOGIN_TODO_SUCCESS="LOGIN_TODO_SUCCESS";
export const LOGIN_TODO_ERROR="LOGIN_TODO_ERROR";

export const GETLOGIN_TODO_LOADING="GETLOGIN_TODO_LOADING";
export const GETLOGIN_TODO_SUCCESS="GETLOGIN_TODO_SUCCESS";
export const GETLOGIN_TODO_ERROR="GETLOGIN_TODO_ERROR";

export const GETCART_LOADING="GETCART_LOADING";
export const GETCART_SUCCESS="GETCART_SUCCESS";
export const GETCART_ERROR="GETCART_ERROR";

export const GET_LAB_TEST="GET_LAB_TEST";
export const LOADING_LAB_TEST="LOADING_LAB_TEST";
export const ERROR_LAB_TEST="ERROR_LAB_TEST";

export const LOGOUT="LOGOUT";